# Generated by Django 4.1.5 on 2023-01-15 06:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("categoryName", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Trips",
            fields=[
                (
                    "tripsID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pickUpCity", models.CharField(max_length=50)),
                ("pickupLocation", models.CharField(max_length=100)),
                ("destinationCity", models.CharField(max_length=50)),
                ("destinationLocation", models.CharField(max_length=100)),
                (
                    "pickupDateTime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "tripCate",
                    models.CharField(
                        choices=[
                            ("ScheduleTrips", "ScheduleTrips"),
                            ("FinishedTrips", "FinishedTrips"),
                            ("OngoingTrips", "OngoingTrips"),
                            ("CanceledTrips", "CanceledTrips"),
                        ],
                        max_length=20,
                    ),
                ),
                ("startingTime", models.TimeField()),
                ("guestPickedUp", models.BooleanField(default=False)),
                ("endTime", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="VehicleDetails",
            fields=[
                (
                    "vehicleDetailsID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vehicleCategory", models.CharField(max_length=50)),
                ("vehicleBrand", models.CharField(max_length=50)),
                ("vehicleModel", models.CharField(max_length=50)),
                ("vehicleModelYear", models.IntegerField()),
                ("vehiclePlateNo", models.CharField(max_length=30)),
                ("assigned", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver",
                        to="API.usermodel",
                    ),
                ),
            ],
        ),
    ]
