# Generated by Django 4.1.5 on 2023-01-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_category_trips_vehicledetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledetails",
            name="vehicleBrand",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="vehicledetails",
            name="vehicleModel",
            field=models.CharField(max_length=30),
        ),
    ]
