# Generated by Django 4.1.5 on 2023-01-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_alter_vehicledetails_vehiclebrand_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="trips", name="endTime",),
        migrations.RemoveField(model_name="trips", name="startingTime",),
    ]
